plugins:
  - rubocop-performance
  - rubocop-rspec

inherit_from:
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml

AllCops:
  UseCache: True
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    # Ignore local files for faster processing
    - 'tmp/**/*'
    - 'out/**/*'
    - 'coverage/**/*'
